name: CI

on:
  - pull_request

jobs:

  typecheck:
    name: Typecheck
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1

      - name: Set up Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - uses: actions/cache@v2
        id: node-modules-cache
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules

      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Typecheck
        run: |
          yarn typecheck

  test-build:
    name: Test production build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1

      - name: Set up Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - uses: actions/cache@v2
        id: node-modules-cache
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules

      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Build
        run: |
          yarn build
